name: fireboy_and_watergirl
description: "A cooperative puzzle-platformer game inspired by Fireboy and Watergirl, built with Flutter and Flame."
homepage: "https://github.com/DomingoMG/fireboy_watergirl_flutter"
repository: "https://github.com/DomingoMG/fireboy_watergirl_flutter"
issue_tracker: "https://github.com/DomingoMG/fireboy_watergirl_flutter/issues"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  gap: ^3.0.1
  flame: ^1.25.0
  flame_audio: ^2.11.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: custom_font
      fonts:
        - asset: assets/fonts/custom_font.TTF
  assets:
    - assets/audio/
    - assets/images/background/
    - assets/images/buttons/
    - assets/images/characters/
    - assets/images/doors/
    - assets/images/elevators/buttons/
    - assets/images/elevators/horizontal/
    - assets/images/elevators/vertical/
    - assets/images/gems/
    - assets/images/levers/
    - assets/images/misc/
    - assets/images/puddles/
    - assets/images/terrain/
    - assets/images/levels/
